name: 'Review'
description: 'Run a Barney review job'
inputs:
  barney-api-server:
    description: 'Barney API server to use'
    required: true
  bsy-compat-server:
    description: 'bsy compatibility server to use'
    required: false
  image:
    description: 'Review image to build'
    required: true
    default: 'test'
outputs:
  status:
    description: 'The review job status'
runs:
  using: 'node16'
  main: 'dist/index.js'
